#!/bin/bash
# install mm locally

ln -sf /root/mm/mm      /usr/bin/mm
ln -sf /root/mm/mmd     /usr/bin/mmd
ln -sf /root/mm/lib/all /usr/bin/mmlib
sed -i '/mm-autocomplete.sh/d' /root/.bashrc
echo ". /root/mm/mm-autocomplete.sh" > /root/.bashrc
