#!/bin/bash
# install mm locally by symlinking from this location (no copy!)

DIR=`realpath ${0%install}`

# mm expects to be in /root/mm, but if it's somewhere else, just link it.
[[ $DIR != /root/mm ]] && sudo ln -snf $DIR /root/mm

sudo ln -snf $DIR/mm      /usr/bin/mm
sudo ln -snf $DIR/mmd     /usr/bin/mmd
sudo ln -snf $DIR/lib/all /usr/bin/mmlib

for f in ~/.bashrc /root/.bashrc; do
	sudo sed -i '/mm-autocomplete.sh/d' $f
	echo ". $DIR/mm-autocomplete.sh" | sudo tee -a $f >/dev/null
done
