#!/bin/bash
# perform ambiguous mm commands (like eg. mysql) on deployment instead of on machine.

[[ $THIS_DEPLOY ]] || THIS_DEPLOY=`basename "$(readlink deploy)"`
export THIS_DEPLOY

MM_DEPLOY=1 mm "$@"
