#!/bin/bash
# ["D1 ..."] :: prepare deploy(s)
. mmlib

deploy_prepare() {
	local D="$1"
	deploy_vars_upload "$D"

	say; say "Uploading SSL CA..."; indent
	SRC_DIR=var/./.acme.sh.etc/ca DST_MACHINE=$MD \
		DST_DIR=/root rsync_dir
	outdent
	say; say "SSH into machine..."
	ssh_to "$MD" bash -s << EOF

shopt -s nullglob
set -o pipefail

DEBUG=$DEBUG
VERBOSE=$VERBOSE

$VARS

$(cat lib/die.sh)
$(cat lib/fs.sh)
$(cat lib/apt.sh)
$(cat lib/ssh.sh)

apt_get_update
apt_get_install git
ssh_git_keys_update_for_user root

if [ ! -d /opt/mm ]; then
	must git clone git@github.com:allegory-software/many-machines2.git /opt/mm
else
	must cd /opt/mm
	must git pull
fi

/opt/mm/mma mm-install

must mma prepare

EOF
}

[ "$1" ] || die "MACHINE or DEPLOY required."
each_machine "$1" machine_prepare
