#!/bin/bash
# ["MD1 ..."] :: list deployments as found on machines
. mmlib

machine_deploy_info_header
try_machine_deploys_info() {
	local s
	if s="$(ssh_script $1 "machine_deploys_info" 2>&1)"; then
		printf "%s\n" "$s"
	else
		read -r s <<< "$s" # first line only
		MACHINE=$1 machine_deploy_info_line_fail "-" "$s"
	fi
}
QUIET=1 each_machine "$1" try_machine_deploys_info
