#!/bin/bash
# list machines
. mmlib

FMT="%-10s %-6s %-11s\n"

printf "$FMT" "MACHINE" "ACTIVE" "PUBLIC_IP"

print_machine() {
	IP=`cat var/machines/$1/public_ip`
	[ -f var/machines/$1/active ] && ACTIVE=Y || ACTIVE=N
	printf "$FMT" "$MACHINE" "$ACTIVE" "$IP"
}
QUIET=1 INACTIVE=1 each_machine "$1" print_machine
