#!/bin/bash
# list machines
. mmlib

FMT="%-10s %-6s %-15s %s\n"

printf "$FMT" MACHINE ACTIVE PUBLIC_IP DEPLOYS

deploys_on() { # MACHINE
	active_deploys
	local ds=()
	local d; for d in $R1; do
		machine_of $d
		[[ $R1 == $1 ]] && ds+=($d)
	done
	R1=`IFS=', '; printf "%s" "${ds[*]}"`
}

print_machine() {
	local IP=`cat var/machines/$1/public_ip`
	local ACTIVE; [ -f var/machines/$1/active ] && ACTIVE=Y || ACTIVE=-
	deploys_on $1; local DEPLOYS="$R1"
	printf "$FMT" "$MACHINE" "$ACTIVE" "$IP" "$DEPLOYS"
}
QUIET=1 INACTIVE=1 each_machine "$1" print_machine
