#!/bin/bash
. mmlib

MD="$1"; checkvar MD

machine_vars_upload "$MD"

SRC_DIR=var/.acme.sh.etc/ca DST_MACHINE=$MD DST_DIR=/root/.acme.sh.etc/ca rsync_dir

ssh_to "$MD" bash -s << EOF

shopt -s nullglob
IFS=$'\n\b'

DEBUG=$DEBUG
VERBOSE=$VERBOSE
$VARS

$(cat lib/die.sh)
$(cat lib/fs.sh)
$(cat lib/apt.sh)
$(cat lib/ssh.sh)

apt_get_update
apt_get_install git
ssh_git_keys_update

if [ ! -d /opt/mm ]; then
	must git clone git@github.com:allegory-software/many-machines2.git /opt/mm
else
	must cd /opt/mm
	must git pull
fi

/opt/mm/mm install

must mma prepare

EOF
