#!/bin/bash
# ["MD1 ..."] :: prepare machine(s)
. mmlib

machine_prepare() {
	MD="$1"; checkvar MD
	machine_vars_upload $MD

	say; say "Uploading SSL CA..."; indent
	#ssh_bash $MD mkdir -p /root/.acme.sh.etc
	SRC_DIR=var/./.acme.sh.etc/ca DST_MACHINE=$MD \
		DST_DIR=/root rsync_dir
	outdent
	say; say "SSH into machine..."
	ssh_to "$MD" bash -s << EOF

shopt -s nullglob
IFS=$' \n\b'

DEBUG=$DEBUG
VERBOSE=$VERBOSE

$VARS

$(cat lib/die.sh)
$(cat lib/fs.sh)
$(cat lib/apt.sh)
$(cat lib/ssh.sh)

apt_get_update
apt_get_install git
ssh_git_keys_update_for_user root

if [ ! -d /opt/mm ]; then
	must git clone git@github.com:allegory-software/many-machines2.git /opt/mm
else
	must cd /opt/mm
	must git pull
fi

/opt/mm/mma mm-install

must mma prepare

EOF
}

[ "$1" ] || die "Refusing to prepare all machines."
each_machine "$1" machine_prepare
