#!/bin/bash
# ["MD1 ..."] :: check if mm's ssh public key is uploaded
. mmlib

FMT="%-10s %s\n"

check_pubkey() {
	local MACHINE=$1
	local PUBKEY="$2"
	local UP_PUBKEY="$(must ssh_to $MACHINE mma ssh-pubkey mm root)" || die "[$?]"
	local OK; [ "$PUBKEY" == "$UP_PUBKEY" ] && OK=Y || OK=N
	printf "$FMT" $MACHINE $OK
}

printf "$FMT" "MACHINE" "OK?"
catfile var/mm_ssh_key.pub
QUIET=1 each_machine "$1" check_pubkey "$R1"
