#!/bin/bash
# ["MD1 ..."] :: upload mm's ssh public key into machine(s)
. mmlib

catfile var/mm_ssh_key.pub; PUBKEY="$R1"

pubkey_update() {
	local UP_PUBKEY="$(must ssh_to $1 mma ssh-pubkey mm root)"
	if [ "$UP_PUBKEY" == "$PUBKEY" ]; then
		say "Key is already uploaded."
	else
		machine_vars_upload "$1"
		ssh_to "$1" mma mm-ssh-pubkey-update
		must cp -f var/mm_ssh_key  var/machines/$1/mm_ssh_key.new
		must mv -v --backup=numbered \
			var/machines/$1/mm_ssh_key.new \
			var/machines/$1/mm_ssh_key
	fi
}
each_machine "$1" pubkey_update
