#!/bin/bash
# ["MD1 ..."] ["USER1 ..."] :: print MySQL passwords
. mmlib

USERS="$2"

echo_mysql_pass() {
	local MACHINE=$1
	ssh_script $MACHINE '
USERS="'"$USERS"'"; [ "$USERS" ] || USERS=`echo root; ls -1 /home`
for USER in $USERS; do
	PASS=`mysql_pass $USER`
	[ "$PASS" ] && printf "%-10s %-10s %s\n" "'$MACHINE'" "$USER" "$PASS"
done
true
'
}
printf "%-10s %-10s %s\n" MACHINE USER PASS
QUIET=1 each_machine "$1" echo_mysql_pass
