#!/bin/bash
# ["MD1 ..."] :: prepare a machine for deployments
. mmlib

_prepare() {

	say; acme_ca_upload
	say; mc_conf_upload

	cat_all_varfiles var/machines/$1/vars
	ssh_script $1 "
		${R1[*]}
		machine_prepare
	"

}
each_machine "$1" _prepare
