#!/bin/bash
# ["MD1 ..."] DB "SQL" :: query MySQL database(s)
. mmlib

MD="$1"; shift
DB="$1"; shift
SQL="$1"; shift

do_query() {
	ssh_script $1 "query_on \"$DB\" \"$SQL\""
}
QUIET=1 each_machine "$MD" do_query
