#!/bin/bash
. mmlib

echo_ssh_hostkey_sha() {
	ssh_hostkey "$1"
	R1="$(printf "%s" "$R1" | ssh-keygen -E sha256 -lf -)"
	printf "%-10s %s\n" "$1" "$R1"
}
QUIET=1 each_machine "$1" echo_ssh_hostkey_sha
