#!/bin/bash
# ["MD1 ..."] ["KEYNAME1 ..."] ["USER1 ..."] :: check out ssh public keys
. mmlib

FMT="%-16s %-16s %-22s %-20s %-6s\n"
printf "$FMT" MACHINE USER ...KEY KEYNAME mm-$HOSTNAME
catfile var/ssh_key-mm-$HOSTNAME.pub; MM_PUBKEY="$R1"
QUIET=1 each_machine "$1" ssh_script "ssh_pubkeys \"$FMT\" \"$3\" \"$2\" \"$MM_PUBKEY\""
