#!/bin/bash
# ["MD1 ..."] [KEYNAME] ["USER1 ..."] :: update a ssh public key into machine(s)
. mmlib

KEYNAME="$2"; [ "$KEYNAME" ] || KEYNAME=mm-$HOSTNAME
USERS="$3"
kf=var/ssh_key-$KEYNAME
[ -f $kf ] || {
	say "Key file $kf not found. Using ~/.ssh/id_rsa..."
	cp_file ~/.ssh/id_rsa $kf
	ssh-keygen -y -f $kf > $kf.pub
}
catfile $kf.pub; PUBKEY="$R1"

pubkey_update() {
	local UP_PUBKEY="$(must ssh_script $1 "ssh_pubkey root $KEYNAME; true")"
	if [ "$UP_PUBKEY" == "$PUBKEY" ]; then
		say "SSH public key '$KEYNAME' is there and it's the same."
	else
		ssh_script $1 "ssh_pubkey_update $KEYNAME \"$PUBKEY\" \"$USERS\""
		cp_file $kf  var/machines/$1/ssh_key-$KEYNAME
	fi
}
each_machine "$1" pubkey_update
