#!/bin/bash
# decrypt and unpack var dir
. mmlib

must gpg --decrypt --batch --yes --passphrase-file var-secret var.tar.gz.gpg > var.tar.gz
must tar xzf var.tar.gz --overwrite
must rm var.tar.gz
must chmod 770 var
