#!/bin/bash
# STATUS ;; show mon alerts
. mmlib

FMT="%-10s %s\n"
_f() {
	must cd /root/mm/mon
	local s dir alert
	for dir in alerts notified; do
		for alert in $(ls -1 $dir); do
			local f=$dir/$alert
			[[ "$(find $f -mmin -1440)" == "" ]] && continue
			timeago `stat -c %Y $f`; local t=$R1
			catfile $f; local v=$R1
			s+="$alert=$v ($t) "
		done
	done
	printf "$FMT" "$MACHINE" "$s"
}
printf "$WHITE$FMT$ENDCOLOR" MACHINE ALERTS
QUIET=1 VARS=FMT FUNCS=_f each_machine md_ssh_script _f
