#!/bin/bash
# STATUS ;; show mon alerts
. mmlib

FMT="%-10s %s\n"
_f() {
	local s alert
	for alert in `ls -1 /root/mm/mon/alerts`; do
		local f=/root/mm/mon/alerts/$alert
		timeago `stat -c %Y $f`; local t=$R1
		catfile $f; local v=$R1
		s+="$alert=$v ($t) "
	done
	printf "$FMT" "$MACHINE" "${s:-${GRAY}none$ENDCOLOR}"
}
printf "$WHITE$FMT$ENDCOLOR" MACHINE ALERTS
QUIET=1 VARS=FMT FUNCS=_f each_machine md_ssh_script _f
