#!/bin/bash
# MYSQL | [DB=] TABLE | list MySQL columns
. mmlib

TABLE="$1"
checkvars TABLE

list_cols() {
	ssh_script "MYSQL_PRETTY=1 query_on ${DB:-$DEPLOY} 'show columns from $TABLE'"
}
each_deploy list_cols $TABLE
