#!/bin/bash
# TABLE :: list MySQL columns
. mmlib

TABLE="$1"
checkvars TABLE

list_cols() {
	ssh_script "MYSQL_PRETTY=1 query_on $DEPLOY 'show columns from $TABLE'"
}
QUIET=1 each_deploy list_cols $TABLE
