#!/bin/bash
# MYSQL | DB TABLE | list MySQL columns
. mmlib

DB="$1"
TABLE="$2"
checkvars DB TABLE

list_cols() {
	ssh_script "MYSQL_PRETTY=1 query_on $DB 'show columns from $TABLE'"
}
each_machine list_cols
