#!/bin/bash
# DEPLOY ;; list deployments
. mmlib

FMT="%-10s %-10s %-7s %-10s %-10s %-10s %s\n"
_f() {
	md_var APP; local APP=$R1
	md_var ENV; local ENV=$R1
	md_var APP_VERSION; local APP_VERSION=$R1
	md_var DOMAIN; local DOMAIN=$R1
	local ACTIVE=YES; deploy_is_active || ACTIVE=no
	printf "$FMT" "$MACHINE" "$DEPLOY" "$ACTIVE" "$APP" "$ENV" "$APP_VERSION" "$DOMAIN"
}
printf "$WHITE$FMT$ENDCOLOR" MACHINE DEPLOY ACTIVE APP ENV APP_VERSION DOMAIN
QUIET=1 INACTIVE=1 each_deploy _f
