#!/bin/bash
# list deployments as found locally and on the git remote
. mmlib

INACTIVE=1 each_deploy_custom_list \
	"%-10s %-10s %-10s %-10s %-10s %-10s" \
	APP ENV APP_VER APP_DEPLVER SDK_DEPLVER STATUS
