#!/bin/bash
# BACKUP ;; remove old backups according to retention policy
. mmlib

backup_sweep() {
	mm_var backup_min_age_days     ; local min_age_s=$(( R1 * 3600 * 24 ))
	mm_var backup_min_free_disk_gb ; local min_free_kb=$(( R1 * 1024 * 1024 ))

	local free_kb=`df -l / | awk '(NR > 1) {print $3}'`
	dir_lean_size backups; local used_kb=$(( R1 / 1024 ))
	local must_free=$(( (min_free_kb - free_kb) * 1024 ))
	(( must_free < 0 )) && return 0

	kbytes $must_free
	say "Must free: $R1"

	local d f
	(
	local f
	local now=`date -u +%s`
	for f in `ls backups`; do
		[[ -L backups/$f ]] && continue
		parse_backup_date $f; local d=$R1
		(( d + min_age > now )) && continue
		printf "%s %s\n" $R1 $f
	done
	) | sort -k1n | while read d f; do
		local fsize=`stat -c %s backups/$f`
		DRY=1 rm_file /opt/mm/backups/$f
		must_free=$(( must_free - fsize ))
		(( must_free < 0 )) && break
	done
}

backup_sweep
