#!/bin/bash
# DB BACKUP ; BACKUP_FILE|- [DB] ; backup a database to a local file
. mmlib

BACKUP_FILE=$1 DB=$2
[[ $1 == - ]] && BACKUP_FILE=/dev/stdout
checkvars BACKUP_FILE DB?
rel_path "$BACKUP_FILE" "$PWD0"; BACKUP_FILE=$R1

_f() { ssh_script "mysql_backup_db" ${DB:-$DEPLOY} > "$BACKUP_FILE"; }
NOALL=1 each_md _f
