#!/bin/bash
# DB ;; list MySQL databases
. mmlib

_f() {
	ssh_script "MYSQL_PRETTY=1 query" "
select
	schema_name as db,
	default_character_set_name as charset,
	default_collation_name as collation
from
	information_schema.schemata
where
	schema_name not in ('mysql', 'information_schema', 'performance_schema', 'sys')
"
}
each_machine _f
