#!/bin/bash
# ["DEPLOY1 ..."] :: deploy an app on its target machine
. mmlib

_f() {

	mysql_pass_gen_once var/deploys/$DEPLOY/mysql_pass

	if deploy_var DOMAIN; then
		local DOMAIN=$R1
		acme_cert_upload $MACHINE $DOMAIN
	fi

	deploy_vars
	ssh_script "
		${R1[*]}
		deploy
	"

}
each_deploy _f
