#!/bin/bash
# ["DEPLOY1 ..."] :: deploy an app on its target machine
. mmlib

_deploy() {
	mysql_pass_gen_once var/deploys/$1/mysql_pass
	deploy_vars $1
	ssh_script $1 "
		${R1[*]}
		DEPLOY=$1 deploy
	"
}
each_deploy "$1" _deploy
