#!/bin/bash
# STAT ;; find and report problems
. mmlib

MIN_FREE_HDD_KB=$((1024 * 10000)) # 10 GB
MIN_FREE_RAM_KB=$((1024 *   300)) # 200 MB

nag "Checking for offline machines (port 22) ..."
ONLINE=
OFFLINE=
_f() {
	if is_listening 22; then
		ONLINE+=" $MACHINE"
	else
		OFFLINE+=" $MACHINE"
	fi
}
QUIET=1 NOSUBPROC=1 each_machine _f
[[ $OFFLINE ]] && say "OFFLINE (port 22):$OFFLINE"

# work only with online machines from here on.
MACHINES=$ONLINE

nag "Checking machines: $MACHINES ..."

_add_full() {
	local FREE_${1}_KB=`ssh_script "get_FREE_${1}_KB"`
	(( FREE_${1}_KB < MIN_FREE_${1}_KB )) && FULL+=" $MACHINE"
}
check_full() {
	nag "Checking for $1 full (< $((MIN_FREE_${1}_KB / 1024)) MB) ..."
	local FULL=
	QUIET=1 NOSUBPROC=1 each_machine _add_full $1
	[[ $FULL ]] && say "$1 FULL (< $((MIN_FREE_${1}_KB / 1024)) MB):$LIGHTRED$FULL$ENDCOLOR"
}
check_full HDD
check_full RAM

nag "Checking for services that are down ..."
mm status | grep !

nag "Checking for deployments that are down or need updating ..."

