#!/bin/bash
# ADMIN ; BACKUP_DIR DST_MACHINE DST_DEPLOY ; restore deploy files from backup
. mmlib

[[ $1 ]] || die "Usage: mm files-restore BACKUP_DIR DST_MACHINE DST_DEPLOY"
DST_MACHINE=$2 DST_DEPLOY=$3 deploy_files_restore "$1"
