#!/bin/bash
# STATUS ;; list available RAM & HDD
. mmlib

md_custom_list \
	"%12s %-12s %10s %-10s %10s %-10s %12s %-12s" \
	"RAM_RATIO RAM_BAR D00_RATIO D00_BAR D01_RATIO D01_BAR SWAP_RATIO SWAP_BAR"
