#!/bin/bash
# ADMIN SSH ; ["USER1 ..."] ; update git ssh keys on machine(s)
. mmlib

USERS="$1"
_f() {
	git_vars $MACHINE; local VARS=("${R1[@]}")
	ssh_script "
${VARS[*]}
git_keys_update \"$USERS\"
"
}
each_machine _f
