#!/bin/bash
# SSH || make ssh work directly with machines and deployments by name
. mmlib

remove_line '# added by mm' /etc/hosts

update_host() {
	ip_of $MACHINE; local IP=$R1
	printf -v s "%-20s %-20s %s\n" "$IP" "${DEPLOY:-$MACHINE}" "# added by mm"
	append "$s" /etc/hosts
	must catfile var/machines/$MACHINE/ssh_hostkey
	remove_line "$R1" ~/.ssh/known_hosts
	append "$R1"$'\n' ~/.ssh/known_hosts
}
each_machine update_host
each_deploy  update_host

# NOTE: For hosts that don't have the latest mm ssh pubkey, use `mm ssh` or run `mm pubkey-update`.
cp_file var/ssh_key-mm-$HOSTNAME   ~/.ssh/id_rsa
