#!/bin/bash
# ADMIN ;; list ssh host fingerprint SHA of machine(s)
. mmlib

_f(){
	ssh_hostkey $MACHINE
	local s=$(printf "%s" "$R1" | ssh-keygen -E sha256 -lf -)
	printf "%-10s %s\n" $MACHINE "$s"
}
QUIET=1 each_machine _f
