#!/bin/bash
# ADMIN SSH ;; update /etc/hosts and set up SSH for direct access
#
# TODO: this doesn't work because:
# 1. SSH's HostKeyAlgorithms != rsa-sha2-256 and SSH tries ECDSA only and gives up.
# 2. StrictHostKeyChecking=yes, and we're connecting by hostname.
#
. mmlib

remove_line '# added by mm' /etc/hosts

update_host() {
	ip_of $MACHINE; local IP=$R1
	printf -v s "%-20s %-20s %s\n" "$IP" "${DEPLOY:-$MACHINE}" "# added by mm"
	append "$s" /etc/hosts
	must catfile var/machines/$MACHINE/.ssh_hostkey
	ssh-keygen -f ~/.ssh/known_hosts -R $IP
	append "$R1"$'\n' ~/.ssh/known_hosts
}
each_machine update_host
each_deploy  update_host

# NOTE: For hosts that don't have the latest mm ssh pubkey, use `mm ssh` or run `mm pubkey-update`.
cp_file var/ssh_key-$HOSTNAME   ~/.ssh/id_rsa
