#!/bin/bash
# UPDATE | [PACKAGE1 ...] | install package(s)
. mmlib

[[ $1 ]] || {
	functions_with_prefix ${MM_DEPLOY:+deploy_}install_
	printf "%s\n" $R1
	exit
}

_f() {
	if [[ $MM_DEPLOY ]]; then
		deploy_install "$@"
	else
		machine_install "$@"
	fi
}
each_machine_or_deploy _f "$@"
