#!/bin/bash
# STATUS ;; list machines
. mmlib

FMT="%-10s %-7s %-15s\n"
_f() {
	local ACTIVE=YES; machine_is_active || ACTIVE=no
	cat_varfile var/machines/$MACHINE public_ip ; local PUBLIC_IP=$R1
	printf "$FMT" $MACHINE "$ACTIVE" "$PUBLIC_IP"
}
printf "$WHITE$FMT$ENDCOLOR" MACHINE ACTIVE PUBLIC_IP
QUIET=1 INACTIVE=1 each_machine _f
