#!/bin/bash
. mmlib

each_machine md_ssh_script '
THIS_MACHINE=$MACHINE
md_var() {
	if [[ $MACHINE ]]; then
		R1=${!1}
	elif [[ $DEPLOY ]]; then
		R1=${!$DEPLOY__$1}
	else
		die "MACHINE or DEPLOY required"
	fi
}
'"$(cat cmd/mon)"
