#!/bin/bash
# FILES ; [REMOTE_DIR MOUNT_DIR] ; mount remote dir via sshfs
. mmlib

[[ $1 ]] || {
	fmt="%-15s %-15s -> %s\n"
	printf "$WHITE$fmt$ENDCOLOR" MACHINE DIR MOUNT
	mount | grep fuse.sshfs | while read -r line; do
		read -ra fields <<< "$line"
		s=${fields[0]}
		mount=${fields[2]}
		userhost=${s%%:*}
		user=${userhost%@*}
		host=${userhost#*@}
		dir=${s#*:}
		machine_by_ip $host && host=$R1
		printf "$fmt" "$host" "$dir" "$mount"
	done
	exit
}

REMOTE_DIR=$1
MOUNT_DIR=$2
shift 2
checkvars REMOTE_DIR MOUNT_DIR
check_abs_filepath $REMOTE_DIR
rel_path $MOUNT_DIR $PWD0; MOUNT_DIR=$R1
mountpoint -q $MOUNT_DIR && die "Already mounted: $MOUNT_DIR"
must mkdir -p $MOUNT_DIR
_f() {
	ip_of $MACHINE; local HOST=$R1
	SSH_CLOSE=1 ssh_opt; run sshfs -o reconnect "${R1[@]}" root@$HOST${REMOTE_DIR:+:$REMOTE_DIR} $MOUNT_DIR
}
NOALL=1 each_md _f
