#!/bin/bash
# MYSQL PASS ; ["USER1 ..."] ; list MySQL passwords
. mmlib

USERS="$2"

_f() {
	md_ssh_script '
USERS="'"$USERS"'"; [ "$USERS" ] || USERS=`echo root; ls -1 /home`
for USER in $USERS; do
	PASS=`mysql_pass $USER`
	[[ $DEPLOY && $USER == $DEPLOY ]] && deploy=$DEPLOY || deploy=\*
	st=
	[[ $DEPLOY && $USER != root && $MYSQL_PASS ]] && { [[ $MYSQL_PASS == $PASS ]] && st=OK || st=OLD!; }
	[[ ! $DEPLOY && $USER == root && $MYSQL_ROOT_PASS ]] && { [[ $MYSQL_ROOT_PASS == $PASS ]] && st=OK || st=OLD!; }
	[ "$PASS" ] && printf "%-10s %-10s %-10s %-10s %s\n" "'$MACHINE'" "$deploy" "$USER" "$st" "$PASS"
done
true
'
}
printf "$WHITE%-10s %-10s %-10s %-10s %s$ENDCOLOR\n" MACHINE DEPLOY USER PASS_OK PASS
QUIET=1 each_md _f
