#!/bin/bash
# MYSQL ADMIN | backup a database to this machine
. mmlib

_f() {
	checkvars MACHINE
	ssh_script "mysql_backup_db $DEPLOY tmp/$DEPLOY.$$.qp"
	SRC_MACHINE=$MACHINE DST_MACHINE= SRC_DIR=/opt/mm/tmp/./$DEPLOY.$$.qp DST_DIR=/opt/mm/backups/$DEPLOY.$$.qp PROGRESS=1 MOVE=1 rsync_dir
	must mv -v --backup=numbered backups/$DEPLOY.$$.qp backups/$DEPLOY.qp
}
NOALL=1 each_deploy _f
