#!/bin/bash
# MYSQL PASS ;; update the root MySQL password on (all) machines.
. mmlib

FILE=var/mysql_root_pass
must catfile $FILE; PASS=$R1

_f() {
	ssh_script "
		mysql_update_pass localhost root $PASS
		mysql_gen_my_cnf  localhost root $PASS
	"
}
each_machine _f
