#!/bin/bash
# ADMIN MYSQL ; ["USER1 ..."] ; list MySQL passwords
. mmlib

USERS="$2"

_f() {
	ssh_script '
USERS="'"$USERS"'"; [ "$USERS" ] || USERS=`echo root; ls -1 /home`
for USER in $USERS; do
	PASS=`mysql_pass $USER`
	[ "$PASS" ] && printf "%-10s %-10s %s\n" "'$MACHINE'" "$USER" "$PASS"
done
true
'
}
printf "%-10s %-10s %s\n" MACHINE USER PASS
QUIET=1 each_machine _f

# TODO: UPTODATE column
