#!/bin/bash
# ADMIN ;; generate a MySQL password for a deployment
. mmlib

_f() {
	say "Generating MySQL password for $DEPLOY..."
	mysql_pass_gen var/deploys/$DEPLOY/mysql_pass
	say "Now run \`mm mysql-pass-update $DEPLOY\` to make it usable."
}
NOALL=1 each_deploy _f
