#!/bin/bash
# SEE ; [PORT] ; check if a port is open from this machine
. mmlib

PORT=${1:-22}
FMT="%-10s %-16s %-5s %-5s\n"
_f() {
	must md_var PUBLIC_IP; local IP=$R1
	IP=$IP is_listening $PORT && OPEN=YES || OPEN=NO
	printf "$FMT" "$MACHINE" "$IP" "$PORT" "$OPEN"
}
printf "$FMT" "MACHINE" "IP" "PORT" "OPEN"
QUIET=1 each_machine _f
