#!/bin/bash
# UPDATE || prepare a machine for deployments
. mmlib

_f() {

	# install prerequisite modules needed for preinstall hooks to work.
	md_install apt rsync

	# install the rest of the modules.
	must machine_var MODULES
	md_install $R1

}
each_machine _f
