#!/bin/bash
# UPDATE || prepare a machine for deployments
. mmlib

_f() {

	# install prerequisite modules needed for preinstall hooks to work.
	machine_install apt rsync

	# install the rest of the modules.
	checkvars MODULES
	machine_install $MODULES

}
each_machine _f
