#!/bin/bash
# ADMIN ;; install a machine
. mmlib

_f() {

	# install prerequisite modules needed for preinstall hooks to work.
	md_install apt rsync

	# install the rest of the modules.
	must md_var MODULES
	md_install $R1

}
each_machine _f
