#!/bin/bash
# SSH KEYS ; [DEVICE] ["USER1 ..."] ; add a ssh public key on machine(s)
. mmlib

DEVICE=$1 USERS=$2
if [[ $DEVICE ]]; then
	checkvars DEVICE
	must catfile var/devices/$DEVICE/ssh_pubkey
	PUBKEY=$R1
else
	ssh_pubkey
	PUBKEY=$R1
fi

each_machine ssh_script "ssh_pubkey_add" "$PUBKEY" "$USERS"
