#!/bin/bash
# ADMIN SSH ; [DEVICE|"PUBKEY"] ["USER1 ..."] ; update a ssh public key into machine(s)
. mmlib

PUBKEY=$1 USERS=$2
if [[ $PUBKEY ]]; then
	[[ -d "devices/$PUBKEY" ]] && ssh_device_pubkey "$PUBKEY" && PUBKEY=$R1
else
	ssh_usable_keyfile; ssh_pubkey_from_keyfile $R1; PUBKEY=$R1
fi

_f() {
	local type key name
	must ssh_script "ssh_pubkey_find" root "$PUBKEY" | read -r type key name
	if [[ "$type $key" == $PUBKEY ]]; then
		say "SSH public key is already there."
	else
		ssh_usable_keyfile; local KEYFILE=$R1 MACHINE_KEYFILE=$R2
		SSH_KEYFILE=$KEYFILE ssh_script "ssh_pubkey_update" "$PUBKEY" "$USERS"
		cp_file $KEYFILE $MACHINE_KEYFILE
	fi
}
each_machine _f
