#!/bin/bash
# SSH KEYS ; [MACHINE|"PUBKEY"] ["USER1 ..."] ; remove a ssh public key from machine(s)
. mmlib

MACHINE=$1 USERS=$2
checkvars MACHINE
if [[ -d var/machines/$MACHINE ]]; then
	must catfile var/machines/$MACHINE/ssh_pubkey
	PUBKEY=$R1
else
	PUBKEY=$MACHINE
fi

each_machine ssh_script "ssh_pubkey_remove" "$PUBKEY" "$USERS"
