#!/bin/bash
# SSH KEYS ; [MACHINE] ["USER1 ..."] ; add a ssh public key to machine(s)
. mmlib

MACHINE=${1:-$THIS_MACHINE} USERS=$2
checkvars MACHINE
must catfile var/machines/$MACHINE/ssh_pubkey; PUBKEY=$R1

each_machine ssh_script "ssh_pubkey_add" "$PUBKEY" "$USERS"
