#!/bin/bash
# ADMIN SSH ; [DEVICE|"PUBKEY"] ["USER1 ..."] ; update a ssh public key into machine(s)
. mmlib

PUBKEY=$1 USERS=$2

if [[ $PUBKEY ]]; then
	[[ -d "devices/$PUBKEY" ]] && ssh_device_pubkey "$PUBKEY" && PUBKEY=$R1
else
	ssh_usable_keyfile; KEYFILE=$R1
	ssh_pubkey_from_keyfile $KEYFILE; PUBKEY=$R1
	SSH_KEYFILE=$KEYFILE ssh_script "ssh_pubkey_update" "$PUBKEY" "$USERS" "$REMOVE"
fi

_f() {
	if [[ $REMOVE ]]; then
		rm_file $MACHINE_KEYFILE
	else
		cp_file $KEYFILE $MACHINE_KEYFILE
	fi
}
each_machine _f
