#!/bin/bash
# ADMIN SSH ; ["KEYNAME1 ..."] ["USER1 ..."] ; list ssh public keys
. mmlib

KEYNAMES=$1 USERS=$2
FMT="%-16s %-16s %-22s %1s %-20s\n"
printf "$FMT" MACHINE USER ...KEY "" KEYNAME
must catfile var/ssh_key-$HOSTNAME.pub; MM_PUBKEY=$R1
QUIET=1 each_machine ssh_script "ssh_pubkeys" "$FMT" "$USERS" "$KEYNAMES" "$MM_PUBKEY"
