#!/bin/bash
# MYSQL | [DB=] "SQL" | query MySQL database(s)
. mmlib

SQL="$1"
checkvars SQL-

_f() {
	local DB=${DB:-DEPLOY}
	checkvars DB
	ssh_script "query_on $DB" "$SQL"
}
QUIET=1 each_deploy_or_machine _f
