#!/bin/bash
# ADMIN ;; fore-reboot machine using cloud API
. mmlib

gcloud_cli() { # CMD
	local_md_vars ACCESS_TOKEN PROJECT_ID ZONE INSTANCE_NAME
	curl -X POST \
		-H "Authorization: Bearer $ACCESS_TOKEN" \
		-H "Content-Type: application/json" \
		"https://compute.googleapis.com/compute/v1/projects/$PROJECT_ID/zones/$ZONE/instances/$INSTANCE_NAME/$CMD"
}

_f() {
	md_var provider/type; local PROVIDER=$R1
	checkvars PROVIDER
	echo $PROVIDER
	${PROVIDER}_cli reset
}

NOALL=1 each_machine _f
