#!/bin/bash
# DEPLOY ; DEPLOY DATE|latest [DST_DEPLOY] ; restore deploy from backup
. mmlib

[[ $1 ]] || {
	say
	say "Usage: mm restore DEPLOY DATE|latest [DST_DEPLOY]"
	say
	list_deploy_backups
	say
	exit
}
DEPLOY=$1 DATE=$2 DST_DEPLOY=$3 deploy_restore
