#!/bin/bash
# DEPLOY ; [MACHINE|DEPLOY DATE|latest [DST_MACHINE|DST_DEPLOY] [MODULE1,...|all]] ; restore deploy from a backup from this machine
. mmlib

[[ $1 ]] || {
	say
	say "Usage: ${WHITE}mm restore DEPLOY DATE|latest [DST_DEPLOY]$ENDCOLOR"
	say
	list_deploy_backups
	say
	exit
}
MD=$1 DATE=$2 DST_MD=$3
shift 2
shift # note: shift 3 doesn't work when there's 2 args !!!
md_restore "$@"
