#!/bin/bash
# MYSQL | [DB=] "col1,... from ..." | select on a MySQL database
. mmlib

SELECT=$1
checkvars SELECT-

_f() {
	ssh_script "MYSQL_PRETTY=1 query_on ${DB:-$DEPLOY} 'select $SELECT'"
}
each_deploy _f
