#!/bin/bash
# MYSQL | [DB=] "col1,... from ..." | select on a MySQL database
. mmlib

SELECT=$1
checkvars SELECT-

_f() {
	local DB=${DB:-$DEPLOY}
	checkvars DB
	AS_DEPLOY=1 ssh_script "MYSQL_PRETTY=1 query_on $DB 'select $SELECT'"
}
each_deploy_or_machine _f
