#!/bin/bash
# SEE DB APP ; [DB=] [where expr] ; select from session table
. mmlib

WHERE=${1:-1=1}
checkvars WHERE-

each_deploy ssh_query "
select
	token, usr,
	from_unixtime(expires), clientip, ctime
	from sess
	where $WHERE
	order by ctime desc
"
