#!/bin/bash
# ADMIN SSH ; DEVICE ; set device
. mmlib

DEVICE=$1
[[ $DEVICE ]] || say "Current device is: $WHITE$(basename $(readlink device))$ENDCOLOR"
checkvars DEVICE

[[ -d var/devices/$DEVICE ]] || {
	say "Creating new device: $DEVICE ... "
	must mkdir -p var/devices/$DEVICE
	[[ -f /root/.ssh/id_rsa ]] && {
		ssh_pubkey; PUBKEY=$R1
		printf "\n%s\n\n" "$R1"
		save "$PUBKEY"$'\n' var/devices/$DEVICE/ssh_pubkey
	}
}
say "Setting current device to: $DEVICE ... "
ln_file var/devices/$DEVICE device
