#!/bin/bash
# SSH KEYS ; please ; generate a new ssh key for this host
. mmlib

[[ $1 == please ]] || die "Say please."
[[ -L device ]] || die "Run ${WHITE}mm set-device${ENDCOLOR} first."
DEVICE=`basename "$(readlink device)"`
checkvars DEVICE

KEYFILE=$HOME/.ssh/id_rsa
rm_file $KEYFILE.new
rm_file $KEYFILE.new.pub
must ssh-keygen -f $KEYFILE.new -t rsa -b 2048 -C $DEVICE -N ""
mv_file_with_backup $KEYFILE.new $KEYFILE
rm_file $KEYFILE.new.pub

ssh_pubkey; PUBKEY=$R1
printf "\n%s\n\n" "$R1"
save "$PUBKEY"$'\n' var/devices/$DEVICE/ssh_pubkey

say "Done. now run \`mm pubkey-add $DEVICE\` to upload the key on all machines."
