#!/bin/bash
# SSH KEYS ; please ; generate a new ssh key for this host
. mmlib

[[ $1 == please ]] || die "Say please."
[[ $THIS_MACHINE ]] || die "Don't know which machine this is. Run `mm set-machine` first."

KEYFILE=$HOME/.ssh/id_ed25519
rm_file $KEYFILE.new
rm_file $KEYFILE.new.pub
must ssh-keygen -f $KEYFILE.new -t ed25519 -C $THIS_MACHINE -N ""
mv_file_with_backup $KEYFILE.new $KEYFILE
rm_file $KEYFILE.new.pub

ssh_pubkey || die "This should've worked."; PUBKEY=$R1
save "$PUBKEY" var/machines/$MACHINE/ssh_pubkey

say "Done. now run \`mm pubkey-add $MACHINE\` to upload the public key on all machines."
