#!/bin/bash
# SSH ; [list] ; close persistent ssh connection
. mmlib

[[ $1 == list ]] && {
	(cd ~/.ssh && find -name control-* | while read -r f; do
		printf "%s\n" ${f#./control-}
	done)
	exit
}

_f() {
	find ~/.ssh -name control-$MACHINE-* | while read -r f; do
		must rm_file $f
	done
}
QUIET=1 each_md _f
