#!/bin/bash
# ADMIN SSH ; [KEYNAME] ; generate a new ssh key for this host
. mmlib

KEYNAME=${1:-$HOSTNAME}
checkvars KEYNAME

say "Generating a new ssh key labeled '$KEYNAME' ..."
ssh-keygen -q -f var/ssh_key.new -t rsa -b 4096 -C "$KEYNAME" -N ""
mv_file_with_backup var/ssh_key.new     var/ssh_key-$KEYNAME
must rm var/ssh_key.new.pub

say "Now run \`mm pubkey-update\` to make it usable on all machines."
