#!/bin/bash
# ADMIN DOMAIN ; [acme.sh options] ; check/renew SSL certificates for deployment(s)
. mmlib

_f() {
	md_ssh_script '
		deploy_nginx_config
		acme_sh --renew -d $DOMAIN' "$@"
}
each_deploy_with_domain _f "$@"
