#!/bin/bash
# SSL | [acme.sh options] | check/renew SSL certificates for deployment(s)
. mmlib

_f() {
	ssh_script_deploy '
		deploy_nginx_config
		acme_sh --renew -d $DOMAIN' "$@"
}
each_deploy_with_domain _f "$@"
