#!/bin/bash
# SSH ; [REMOTE_PORT] [LOCAL_PORT] [LOCAL_IP] ; ssh tunnel remote port to local port
. mmlib

[[ $1 ]] || {
	printf "${WHITE}%-15s %-6s -> %-6s %s${ENDCOLOR}\n" MACHINE PORT L-PORT L-IP
	ps aux | while read -r line; do
		[[ $line != *autossh* ]] && continue
		read -ra fields <<< "$line"
		for field in "${fields[@]}"; do
			if [[ $field =~ ^[0-9.]+:[0-9]+:[^:]+:[0-9]+$ ]]; then
				IFS=':' read -r LIP LPORT _ RPORT <<< "$field"
			fi
			if [[ $field == root@* ]]; then
				RIP=${field#root@}
			fi
		done
		machine_by_ip $RIP && RIP=$R1
		printf "%-15s %-6s -> %-6s %s\n" ${RIP:-?} ${RPORT:-?} ${LPORT:-?} ${LIP:-?}
	done
	exit
}

REMOTE_PORT=$1 LOCAL_PORT=$2 LOCAL_IP=$3
checkvars REMOTE_PORT LOCAL_PORT? LOCAL_IP?
_f() {
	ip_of $MACHINE; local HOST=$R1
	lsof -i :$LOCAL_PORT >/dev/null && die "Port already bound: $LOCAL_PORT"
	SSH_CLOSE=1 ssh_opt; run autossh "${R1[@]}" -f -N -M 0 -T \
		-L ${LOCAL_IP:-127.0.0.1}:${LOCAL_PORT:-$REMOTE_PORT}:localhost:$REMOTE_PORT \
		root@$HOST
}
each_md _f
