#!/bin/bash
# COMMAND ; [REMOTE_PORT] [LOCAL_PORT] ; ssh tunnel remote port to local port
. mmlib

[[ $1 ]] || {
	printf "${WHITE}%-15s %-6s -> %-6s %s${ENDCOLOR}\n" MACHINE PORT L.PORT L.IP
	ps aux | while read -r line; do
		[[ $line != *autossh* ]] && continue
		read -ra fields <<< "$line"
		for field in "${fields[@]}"; do
			if [[ $field =~ ^[0-9]+:[^:]+:[0-9]+$ ]]; then
				IFS=':' read -r LPORT LIP RPORT <<< "$field"
			fi
			if [[ $field == root@* ]]; then
				RIP=${field#root@}
			fi
		done
		machine_by_ip $RIP && RIP=$R1
		printf "%-15s %-6s -> %-6s %s\n" ${RIP:-?} ${RPORT:-?} ${LPORT:-?} ${LIP:-?}
	done
	exit
}

REMOTE_PORT=$1
LOCAL_PORT=$2
checkvars REMOTE_PORT
shift 2
AS_DEPLOY=1 each_md ssh_to "$@"
