#!/bin/bash
# UPDATE | [PACKAGE1 ...] | install package(s)
. mmlib

[[ $1 ]] || {
	functions_with_prefix ${MM_DEPLOY:+deploy_}install_
	printf "%s\n" $R1
	exit
}
each_machine_or_deploy machine_or_deploy_uninstall "$@"
