#!/bin/bash
# SEE DB APP ; [DB=] [where expr] ; select from usr table
. mmlib

WHERE=${1:-1=1}
checkvars WHERE-

each_deploy ssh_query "
select
	u.usr, t.name tenant, u.active, u.email, u.name, u.phone, u.ctime
	from usr u, tenant t
	where u.anonymous = 0 and $WHERE
	order by u.ctime desc
"
