#!/bin/bash
# SEE DB APP ; [DB=] [where expr] ; select from usrtoken table
. mmlib

WHERE=${1:-1=1}
checkvars WHERE-

each_deploy ssh_query "
select
	token, usr, expires, validates, ctime
	from usrtoken
	where $WHERE
	order by ctime desc
"
