#!/bin/bash
# ADMIN ; [DB=] [where expr] ; select from usrtoken table
. mmlib

WHERE=${1:-1=1}
checkvars WHERE-

each_md ssh_query "
select
	token, usr, expires, validates, ctime
	from usrtoken
	where $WHERE
	order by ctime desc
"
