#!/bin/bash
# ADMIN ;; pack and encrypt var dir to var.tar.gz
. mmlib

must chmod 440 var-secret
must tar czf var.tar.gz var
must gpg --batch --yes --symmetric --cipher-algo AES256 --passphrase-file var-secret var.tar.gz
must rm var.tar.gz
du -sh var.tar.gz.gpg
