#!/bin/bash
# ADMIN MM ; please ; restore previous var dir
. mmlib

[[ $1 == please ]] || die "Say please"
set +f
latest=$(printf "%s\n" var.~*~ | sort -V | tail -1)
set -f
[[ $latest && -d $latest ]] || die "No backup found."
say "Restoring 'var' from '$latest' ..."
mv_dir_with_backup "$latest" var
