#!/bin/bash
# MM VAR ; REPO ; clone var dir (and backup current var dir)
. mmlib

REPO=$1
checkvars REPO

on_exit run rm -rf var.new
git_clone_for root $REPO var.new
must mv --backup=numbered var.new var
must chmod 770 var
