#!/bin/bash
# MM VAR ; [COMMIT-MESSAGE] ; git-push var dir
. mmlib

COMMIT_MSG=${1:-unimportant}

must cd var
must git add .
run git diff --quiet && run git diff --staged --quiet || \
	must git commit -m "$COMMIT_MSG"
must git push
