#!/bin/bash
# ["USER1 ..."] :: copy over root's mc config to all deploy users
. mmlib

USERS="$1"; [ "$USERS" ] || USERS="$(machine_deploys)"
for USER in $USERS; do
	say "Updating mc for: $USER..."
	must mkdir -p /home/$USER/.config
	SRC_DIR=/root/./.config/mc DST_DIR=/home/$USER sync_dir
done
