#!/bin/bash
. mmlib

checkvars MACHINE MYSQL_ROOT_PASS DHPARAM-

# disable clound-init because it resets our changes on reboot.
touch /etc/cloud/cloud-init.disabled

machine_set_hostname $MACHINE
machine_set_timezone UTC

# remount /proc so we can pass in secrets via cmdline without them leaking.
must mount -o remount,rw,nosuid,nodev,noexec,relatime,hidepid=2 /proc
# make that permanent...
must sed -i '/^proc/d' /etc/fstab
append "proc  /proc  proc  defaults,nosuid,nodev,noexec,relatime,hidepid=1  0  0" /etc/fstab

apt_get_install sudo htop mc git nginx curl

# configure nginx
# add dhparam.pem from mm (dhparam is public).
save "$DHPARAM" /etc/nginx/dhparam.pem
# remove nginx placeholder vhost.
must rm -f /etc/nginx/sites-enabled/default
nginx -s reload

# configure git for pushing
git_install_git_up
git_config_user "mm@allegory.ro" "Many Machines"

# allow binding to ports < 1024 by any user.
save 'net.ipv4.ip_unprivileged_port_start=0' \
	/etc/sysctl.d/50-unprivileged-ports.conf
must sysctl --system

must mma mysql-install
must mma tarantool-install

say "Prepare done."
