#!/bin/bash
# ["MD1 ..."] :: prepare machine(s)
. mmlib

machine_prepare() {
	local MD="$1"
	machine_vars_upload $MD

	say; say "Uploading SSL CA..."; indent
	SRC_DIR=var/./.acme.sh.etc/ca DST_MACHINE=$MD \
		DST_DIR=/root rsync_dir
	outdent

	say; say "SSH into machine..."
	ssh_script "$MD" "

$VARS

apt_get_update
apt_get_install git
ssh_git_keys_update root

if [ ! -d /opt/mm ]; then
	must git clone git@github.com:allegory-software/many-machines2.git /opt/mm
else
	must cd /opt/mm
	must git pull
fi

/opt/mm/mma mm-install

must mma prepare

EOF
}

[ "$1" ] || die "MACHINE or DEPLOY required."
each_machine "$1" machine_prepare
